# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KgrFinderDockWidget
                                 A QGIS plugin
Find KGR Data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-09-11
        git sha              : $Format:%H$
        copyright            : (C) 2023 by csgis gbr
        email                : toni.schoenbuchner@csgis.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import pyqtSignal

from qgis.PyQt.QtWidgets import QWidget, QVBoxLayout
from .config_options_page import ConfigOptionsPage


class KgrFinderDockWidget(QWidget):


    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QVBoxLayout()
        self.config_options = ConfigOptionsPage(self)
        layout.addWidget(self.config_options)
        self.setLayout(layout)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()